app/src/main/java/org/brightmindenrichment/street_care/ui/user/ProfileFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/VisitDataAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/VisitFormFragment0.kt
app/src/main/res/layout/card_impact.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/fragment_visit.xml

Impact dashboard firebase update

Impact dashboard updated

---

app/src/main/res/values-night/themes.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/themes.xml

Code fix for the following issues:
Issue 20: Visit log -"How many people did you help" - doesnt has + & - symbol on the yellow buttons.
Issue 23: How to help, Visit log, Community, Profile's font color should be visible maybe Black instead of Yellow
Issue 24: The yellow color for the selected option in nav bar makes it difficult to read, instead we can have a dark shade of yellow for this.

Code fix for issue 20, 23 and 24

---

app/src/main/res/layout/fragment_you_tube_list.xml
app/src/main/res/layout/fragment_youtube_list_item.xml

Fixed issue #9: youtube video scroll.

Visit log dev v2 pratham bugfix

---

app/src/main/java/org/brightmindenrichment/street_care/ui/user/ProfileFragment.kt

Profile stats auto double fixed

Profile stats auto double bug fixed

---

app/src/main/java/org/brightmindenrichment/street_care/ui/user/LoginFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/user/SignUpFragment.kt
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_sign_up.xml

Commented code for social sign-ins as suggested by Shreyas since the firebase issue is not yet fixed.

Visit log dev v2 rishi bug fix

---

app/build.gradle
app/src/main/java/org/brightmindenrichment/street_care/ui/community/AddEventFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/CommunityEventFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/adapter/CommunityRecyclerAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/data/EventDataAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/util/DebouncingQueryTextListener.kt
app/src/main/res/layout/fragment_community_event.xml

What we have done:
1. Implemented a search bar along with its functionality.
2. Fix the bugs:
(a.) 
**Before:** When adding a new event through the app, we would get UNKNOWN UNKNOWN for the month and year, and NA 
for the day on the events list.
**After:** Display the correct month, year, and day on the events list when adding a new event through the app.
(b.)
Changed the format of time display in 'Add Event', ensuring to display the time in the format ”hh:mm”. Taking 9 am as an 
example: 
**Before:** It would display as "9:0". 
**After:** The update, it will display as "09:00".
(c.)
**Before:** When the bottom sheet is expanded, clicking the 'heart button' on the event list does not reflect the result on the 'heart button' on the bottom sheet for the same selected event. Additionally, …

implemented a search bar along with its functionality and fixed bugs.

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/data/VisitLog.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/repository/VisitLogRepositoryImp.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional1.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional10.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional2.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional3.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional5.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional6.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional7.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional8.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional9.kt
app/src/main/res/layout/fragment_additional1.xml
app/src/main/res/layout/fragment_additional10.xml
app/src/main/res/layout/fragment_additional2.xml
app/src/main/res/layout/fragment_additional5.xml
app/src/main/res/layout/fragment_additional6.xml
app/src/main/res/layout/fragment_additional7.xml
app/src/main/res/layout/fragment_additional8.xml
app/src/main/res/layout/fragment_additional9.xml
app/src/main/res/navigation/mobile_navigation.xml
app/src/main/res/values/strings.xml

Updated the visitlog additional question and matched it with the streetcare.us WordPress site.
Fixes: 
1. Created new 6 pages and added them after Additional2 page to match the flow of questions from the WordPress site.
2. Defined new data fields in the visitLog.kt file to store the answers for the newly added questions.
3. Added these data fields in the VisitLogRepositoryImp.kt file so that it can be saved on the Firebase.

Visit log dev v2 updated visit log

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional3.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional4.kt

Fixed the color issue for the buttons.

Fixed the color issue for the buttons.

---

app/src/main/res/drawable/ic_profile.xml
app/src/main/res/layout/fragment_edit_profile.xml
app/src/main/res/layout/fragment_profile.xml

Profile Pic Logo Alignment Bug Fix - Adjusted the dimensions of the profile logo.

Profile Pic Logo Alignment Bug Fix

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/brightmindenrichment/data/local/EventsDatabase.kt
app/src/main/java/org/brightmindenrichment/data/local/dao/EventDao.kt
app/src/main/java/org/brightmindenrichment/street_care/MainActivity.kt
app/src/main/java/org/brightmindenrichment/street_care/MyApplication.kt
app/src/main/java/org/brightmindenrichment/street_care/di/AppModule.kt
app/src/main/java/org/brightmindenrichment/street_care/notification/MyFirebaseMessagingService.kt
app/src/main/java/org/brightmindenrichment/street_care/notification/NotificationWorker.kt
app/src/main/java/org/brightmindenrichment/street_care/notification/NotificationWorkerFactory.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/CommunityEventFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/model/DatabaseEvent.kt
app/src/main/java/org/brightmindenrichment/street_care/util/Constants.kt
app/src/main/java/org/brightmindenrichment/street_care/util/DataStoreManager.kt
app/src/main/java/org/brightmindenrichment/street_care/util/Extensions.kt
app/src/main/java/org/brightmindenrichment/street_care/util/NotificationID.kt
app/src/main/res/layout/fragment_community.xml
build.gradle

To ensure users receive notifications even when the app is inactive (in the background or terminated), I've implemented a background service that runs periodically to monitor the collection. The service will run every 12 hours for battery efficiency.

Improve notification yen

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/data/VisitLog.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/repository/VisitLogRepositoryImp.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment4.kt
app/src/main/res/layout/fragment_visit_form4.xml

Added the new tags in the Visitlog question 4 to be in sync with the webapp.

Visit log dev v2 sync visit log

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/data/VisitLog.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/repository/VisitLogRepositoryImp.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment2.kt
app/src/main/res/layout/fragment_visit_form2.xml

Added time feature in question 2 in the Visit Log Page

Visit Log - Added time feature in question 2

---

app/src/main/java/org/brightmindenrichment/street_care/MainActivity.kt

fix the issue that the app will crash if users turn off the notification.

Notification bug fix

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/VisitDataAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/data/VisitLog.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/repository/VisitLogRepositoryImp.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment5.kt
app/src/main/res/layout/fragment_visit_form5.xml

Rating system changed to five star rating

Rating changes amisha

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/VisitDataAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/data/VisitLog.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/repository/VisitLogRepositoryImp.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional8.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment1.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment2.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment4.kt
app/src/main/res/layout/fragment_visit_form1.xml
app/src/main/res/layout/fragment_visit_form2.xml
app/src/main/res/layout/fragment_visit_form3.xml
app/src/main/res/values/strings.xml

Reverts BrightMindEnrichment/StreetCare#49

Revert "Visit log dev v2 Test"

---

app/src/main/java/org/brightmindenrichment/street_care/ui/community/CommunityFragment.kt
app/src/main/res/layout/fragment_community.xml

Removed the 'Search' feature.
Redesigned layout and user interface for the events section.
Eliminated the 'Activity' section, including the 'Recycler View' and 'View All' button.

Community Section Changes

---

app/src/main/java/org/brightmindenrichment/street_care/ui/user/ProfileFragment.kt

bugfix for delete Google account w Firebase
previously a NPE occurred when retrieving the google credentials with GoogleSignIn.getLastSignedInAccount(it)
Instead creating a GoogleSignInOptions.Builder launching an intent and retrieving signed in user google credentials to then reauth in Firebase and proceed to delete account.

fix Google reAuth and delete account flow

---

app/src/main/java/org/brightmindenrichment/street_care/ui/community/CommunityFragment.kt

[https://github.com/BrightMindEnrichment/StreetCare/issues/60](url)

Access approximate location check

---

app/src/main/java/org/brightmindenrichment/street_care/ProfileBadges.kt
app/src/main/res/layout/fragment_profile_badges.xml

Fixed the layout alignment of Badges in profile page.

Badges alignment fix

---

app/src/main/java/org/brightmindenrichment/street_care/MainActivity.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/AddHelpRequestFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/data/HelpRequestDataAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/util/Queries.kt

Code changes to helpRequestsAndroid collection to helpRequests

Help requests code modify collections

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/VisitDataAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/repository/VisitLogRepositoryImp.kt

Changing the collection name from interimPersonalVisitLog to VisitLogs

Modifying collection name for VisitLogs

---

app/src/main/java/org/brightmindenrichment/street_care/ui/user/ProfileFragment.kt
app/src/main/res/layout/card_impact.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/values/strings.xml

Alignment fix and Fetch username on Profile page

Alignment fix and Fetch username on Profile page 

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional3.kt

last page of additional questions answer is not being captured at the UI level

Highlighting the selected option

---

app/src/main/res/values/strings.xml

Modifying string literals for the android application

Modifying string literals

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/VisitDataAdapter.kt

app is crashing on opening the profile page after user login and Visit log page

Fixing app crash

---

app/src/main/java/org/brightmindenrichment/street_care/ProfileMyEvents.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/AddEventFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/data/EventDataAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/util/Queries.kt
app/src/main/res/layout/bottom_sheet_event.xml
app/src/main/res/layout/event_list_layout.xml

Temporary changes for outreach events collection and hiding the register button from future events

---

app/src/main/java/org/brightmindenrichment/street_care/ui/user/ProfileFragment.kt
app/src/main/res/drawable/icon_edit.xml
app/src/main/res/layout/card_signin.xml
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/fragment_what_to_give.xml

Fixes for the first 5 issues for the profile page 
https://docs.google.com/document/d/1TpkA7dxfEdLB2toWleWVP5yu8PgNxmw-WV3ASM7AG0I/edit?pli=1

fix UI issues in Profile page layout xml

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/details/VisitLogDetailsFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/details/VisitLogDetailsViewModel.kt

Refactoring VisitLogDetailsFragment and VisitLogDetailsViewModel to use the MVVM architectural pattern

visit log details code refactor

---

app/src/main/java/org/brightmindenrichment/street_care/ui/community/CommunityEventFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/CommunityHelpRequestFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/util/Queries.kt

https://github.com/user-attachments/assets/930e07b4-e615-4fc0-85b1-70ff5adba75f

Filter by skill

---

app/src/main/java/org/brightmindenrichment/street_care/ui/user/LoginFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/user/SignUpFragment.kt
app/src/main/res/layout/card_signin.xml

Removed Twitter button from Andriod app's Sign in page due to token issues

Removed Twitter button from Sign in page due to token issues

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/SurveySubmittedFragment.kt
app/src/main/res/values-es/strings.xml
app/src/main/res/values/strings.xml

optimized accordingly, adding strings to strings and es/strings xml files

optimized_share_with_community

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/Additional3.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/SurveySubmittedFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment5.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitViewModel.kt

Was initially facing issues with data going onto collection as only NULL values

---

app/src/main/java/org/brightmindenrichment/street_care/ui/community/AddEventFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/AddHelpRequestFragment.kt
app/src/main/res/values-es/strings.xml
app/src/main/res/values/strings.xml

the following fields will not be mandatory:  Contact Number, Address, Street, Zip Code However, State and City will remain mandatory.

Updating mandatory fields of address as per the request

---

app/src/main/java/org/brightmindenrichment/street_care/ui/community/AddEventFragment.kt
app/src/main/res/layout/fragment_add_event.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values/strings.xml

[autocomplete address Android.webm](https://github.com/user-attachments/assets/8f3730cf-47de-4b63-a155-5c954313e4a1)

Android - adding autocomplete of address in community page add event

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment1.kt
app/src/main/res/drawable/field_border.xml
app/src/main/res/layout/fragment_visit_form1.xml

In Visit Log's "Where was your Visit" page - updated the design to match iOS, auto-completing the address (city, state and zipcode) and removed 'Select Location' button
[6.webm](https://github.com/user-attachments/assets/59b0e7a3-c4f3-4e97-904d-6f0b21909656)

Android - Visit log auto populating address in "where was your visit" page and 

---

app/src/main/java/org/brightmindenrichment/street_care/ui/community/AddEventFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/CommunityEventFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/adapter/CommunityRecyclerAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/data/Event.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/data/EventDataAdapter.kt
app/src/main/res/drawable/unflag.xml
app/src/main/res/layout/bottom_sheet_event.xml
app/src/main/res/layout/event_list_layout.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values/strings.xml

Edited user based flagging, synchronized webapp and android for flagging, updated List view flagging in Community page

Android - Updated Flagging Events functionality in Community Page

---

app/src/main/java/org/brightmindenrichment/street_care/ui/community/CommunityEventFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/adapter/CommunityRecyclerAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/data/Event.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/data/EventDataAdapter.kt

Updated Future and Past Events to show location in "City, State" format only. No full location

Android- Outreach Events - emoved full address - show only City,State

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/data/VisitLog.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/repository/VisitLogRepositoryImp.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment1.kt
app/src/main/res/drawable/button_next.xml
app/src/main/res/drawable/button_outline_background.xml
app/src/main/res/drawable/button_previous.xml
app/src/main/res/drawable/field_border.xml
app/src/main/res/drawable/ic_search.xml
app/src/main/res/layout/fragment_visit_form1.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Android - Visitlog design change for question2 - Where was your Interaction

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/data/VisitLog.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment3.kt
app/src/main/res/drawable/baseline_add_24.xml
app/src/main/res/drawable/baseline_horizontal_rule_24.xml
app/src/main/res/drawable/description_rectangle_bg.xml
app/src/main/res/drawable/rounded_btn.xml
app/src/main/res/drawable/rounded_btn_background.xml
app/src/main/res/layout/fragment_visit_form3.xml
app/src/main/res/navigation/mobile_navigation.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Updated design changes on Question 3

Seetha design changes question3

---

app/src/main/java/org/brightmindenrichment/street_care/MainActivity.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/user/LoginFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/VisitFormFragment0.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/LoginRedirectFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/LoginVisitLogFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/SurveySubmittedFragment.kt
app/src/main/res/drawable/dialog_bg.xml
app/src/main/res/drawable/dialog_ph.xml
app/src/main/res/drawable/oval_text_view.xml
app/src/main/res/layout/dialog_custom_login.xml
app/src/main/res/layout/dialog_login_2.xml
app/src/main/res/layout/dialog_provided_help.xml
app/src/main/res/layout/fragment_login_redirect.xml
app/src/main/res/layout/fragment_login_visit_log.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/fragment_visit.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/navigation/mobile_navigation.xml
app/src/main/res/navigation/profile.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Updated Login Page for VisitLog

Login updates visit log

---

app/src/main/res/layout/fragment_survay_submitted.xml
app/src/main/res/layout/fragment_visit_form3.xml
app/src/main/res/navigation/mobile_navigation.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values/strings.xml

Updated the Last screen - survey submitted

Android - updated design for Survay submitted screen, adjusted font for Q3

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/VisitFormFragment0.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/LoginVisitLogFragment.kt

Changes on Back Button

---

app/src/main/java/org/brightmindenrichment/street_care/ui/user/ProfileFragment.kt

Removing back button profile

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment5.kt
app/src/main/res/drawable/empty_star.xml
app/src/main/res/drawable/filled_star.xml
app/src/main/res/drawable/rectangle_comment_box.xml
app/src/main/res/layout/fragment_visit_form5.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

New Branch for Question6

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/data/VisitLog.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/repository/VisitLogRepositoryImp.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitFormFragment5.kt

Comments are saved to firebase

Comments getting saved in Q6

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/VisitDataAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/data/VisitLog.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/VisitLogRecyclerAdapter.kt
app/src/main/res/drawable/status_background.xml
app/src/main/res/layout/visit_log_list_layout.xml
app/src/main/res/values/colors.xml

Published, Pending and Rejected tags based on Approved, Pending and Rejected status fields.

Tags for interaction logs based on status field value

---

app/src/main/java/org/brightmindenrichment/street_care/ui/visit/VisitDataAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/visit/details/VisitLogDetailsViewModel.kt

With these changes, interaction logs created in web app will be displayed on mobile app's interaction log tab. Similarly, log deletion is also handled.
**Interaction logs created in web app:**
**Same Interaction logs displayed in mobile app:**
**Flagging Public Interaction log:**
**Deleting log in mobile app:**
https://github.com/user-attachments/assets/f6367a44-a23a-4f3a-86b0-05379313d784

Changes for webapp interaction log not displaying on mobile app

---

app/src/main/java/org/brightmindenrichment/street_care/ui/home/HomeFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/user/ChapterMembershipFormOneAcitivity.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/user/ChapterMembershipFormThreeAcitivity.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/user/ChapterMembershipFormTwoAcitivity.kt
app/src/main/res/layout/banner_verification.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values/strings.xml

**Created 'Become a member' button on the Get Verified banner for chapter membership form submission**
https://github.com/user-attachments/assets/d596cc75-cfbc-4bf7-8235-a83f3ec6c5c6
**Submitted form details in Firestore and BME_Form_Data sheet:**

 Become a member button - Chapter membership

---

app/src/main/java/org/brightmindenrichment/street_care/ui/user/ProfileFragment.kt
app/src/main/res/layout/fragment_profile.xml

Badges earned feature added back in profile page

Added badges earned feature back in profile page

---

app/src/main/java/org/brightmindenrichment/street_care/ui/community/CommunityEventFragment.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/adapter/CommunityRecyclerAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/data/Event.kt
app/src/main/java/org/brightmindenrichment/street_care/ui/community/data/EventDataAdapter.kt
app/src/main/java/org/brightmindenrichment/street_care/util/DialogUtils.kt
app/src/main/res/layout/bottom_sheet_event.xml
app/src/main/res/layout/event_list_layout.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values/strings.xml

In Outreach events page, when a logged-in user taps Like, update Firebase (increment like count and mark user’s like, vice versa). When a guest users taps Like, redirect to profile page with popup message prompting them to login/signup.
https://github.com/user-attachments/assets/ece7f31a-6012-46cf-8324-204f6fb559cd

Save likes feature
